### ISSUE TITLE
Optimize the creation of the following attribute

### ISSUE THREAD

**Issue by k0pernicus** [yoann-dufresne/AMIC2#1]
https://github.com/yoann-dufresne/AMIC2/blob/58d225d6f4cb1141a80139f505925fed6becd0c2/game.py#L5

Using `itertools`, there is a performance difference because it uses lists whose elements refer to same id.
Also, you are using a generator (`range`) and allocate memory for a simple declaration/allocation.

This is the performance benchmark:
```
>>> from timeit import timeit
>>> timeit("[False for _ in range(8)]")
0.6544774020003388
>>> timeit("[False] * 8")
0.1485445250000339
```

So, I suggest for this line of code to update `[False for _ in range(nb_scene)]` by `[False] * nb_scene`.

**Comment by yoann-dufresne** [comment]
You are totally right !
I changed it in the next commit :)
